### ISSUE TITLE
Fix codecov step

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#10]
No longer works:

```yml
- name: Test coverage
      if: inputs.run_covr == 'true' && inputs.runner_os == 'Linux'
      run: |
        covr::codecov()
      shell: Rscript {0}
```
