### ISSUE TITLE
rworkflows_static: failing on Linux with `setup-bioc`

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#42]
## 1. Bug description

rworkflows_static: failing on Linux with `grimbough/bioc-actions/setup-bioc@v1`

### Console output 

Can't find any informative outputs from this action.

```
Error: Process completed with exit code 2.
```

https://github.com/neurogenomics/rworkflows/actions/runs/3901770258/jobs/6664019209#step:7:1

**Comment by bschilder** [comment]
Might be a simple yaml syntax error, since this step should't even be run on Linux:

```yml
  - name: Setup R and Bioconductor
      if: inputs.runner_os != 'Linux'
      uses: grimbough/bioc-actions/setup-bioc@v1
      with:
        bioc-version: ${{ matrix.config.bioc }}
```
