### ISSUE TITLE
Consider implementing `workflow-telemetry-action`

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#51]
https://github.com/runforesight/workflow-telemetry-action

![Screenshot 2023-03-03 at 11 45 43](https://user-images.githubusercontent.com/34280215/222712440-48498d95-e85b-444d-affb-09436258e4a7.png)

**Comment by bschilder** [comment]
Implemented on dev, and added an arg to make sure the `rworkflows` action doesn't fail if it stops working (since this is a non-critical step).


```yml
   - name: Collect Workflow Telemetry 🔭
      uses: runforesight/workflow-telemetry-action@v1
      continue-on-error: true
```
