### ISSUE TITLE
Explore nested GHA inputs

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#79]
As the `rworkflows` actions gets more comprehensive, the parameter list continue to grow. It might be better to nest these arguments in some way.

Ways to do this:
1. Create separate subactions that users can supply inputs to at each step. #4
2. Nest inputs within the main rworkflow action: e.g. 

in the workflow
```yml
 steps:
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: ${{ false }}
           opt_1: ${{ false }}
           opt_2: 'myoption'
``` 

in the action:
```
inputs.run_bioccheck.opt_2
```

Not sure if this syntax is supported by GHA though.

Documentation:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
