### ISSUE TITLE
Make Docker step less redundant

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#9]
Currently, I build the Docker container twice (once in the beginning of the Linux workflow, and again via the `docker/build-push-action@v1` step. Would be more efficient to just push the first one.

**Comment by bschilder** [comment]
Should also upgrade the action. This step may help:

https://github.com/Bioconductor/bioconductor_docker/blob/RELEASE_3_16/.github/workflows/build_containers.yaml#L28

**Comment by bschilder** [comment]
Related issue:
https://github.com/docker/setup-buildx-action/issues/251

**Comment by bschilder** [comment]
Tried many variations of this, all of them ran into the same error regarding being unable to find Docker executable. 

@almahmoud do you have any insights for how to overcome these issues on GHA?

```yml
#### Docker registry steps ####
    - name: 🐳🛠 Set up Docker Buildx
      if: |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux'
      uses: docker/setup-buildx-action@v3
        
    - name: 🐳🛠 Set up QEMU
      if: |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      
    - name: 🐳🔐 Log in to the Github Container registry - ghcr.io
      if : |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux' && inputs.docker_registry == 'ghcr.io'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GITHUB_TOKEN }}
        
    - name: 🐳🔐 Log in to the Github Container registry - docker.io
      if: |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux' && inputs.docker_registry == 'docker.io'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.docker_user }}
        password: ${{ inputs.DOCKER_TOKEN }}  
      
    - name: 🐳✏️ Create Docker file 
      if: |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux'
      run: |
        options(crayon.enabled = TRUE)
        if(!require("rworkflows", quietly=TRUE)) remotes::install_github("neurogenomics/rworkflows")
        path <- rworkflows::use_dockerfile()
      shell: Rscript {0} 
      
    - name: 🐳🚀 Build and push to Docker registry 
      if: |
        (!contains(github.event.head_commit.message, '[nodocker]')) && inputs.run_docker == 'true' && runner.os == 'Linux'
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags: |
          ${{ inputs.docker_registry }}/${{ inputs.docker_org }}/${{ env.packageName }}:${{ env.packageVersion }},
          ${{ inputs.docker_registry }}/${{ inputs.docker_org }}/${{ env.packageName }}:latest
        build_args: |
          PKG=${{ env.packageNameOrig }},
          BASE_IMAGE=${{ matrix.config.cont }}
```
